# Generated by Django 5.2b1 on 2025-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_place', models.CharField(max_length=255, verbose_name='Где собираемся')),
                ('what_to_do', models.TextField(verbose_name='Чем займёмся')),
                ('link', models.URLField(verbose_name='Ссылка на место/ мероприятие')),
                ('date_meeting', models.DateField(auto_now=True, verbose_name='Когда собираемся')),
            ],
        ),
    ]
