# Generated by Django 5.2b1 on 2025-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_date_create_alter_meeting_date_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='reason_to_meet',
            field=models.CharField(default=0, max_length=150, verbose_name='Повод для встречи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_place',
            field=models.CharField(max_length=255, verbose_name='Место сбора'),
        ),
    ]
