# Generated by Django 5.2b1 on 2025-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_address_meeting_reason_to_meet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='dress_code',
            field=models.CharField(default=0, max_length=150, verbose_name='Дресс-код'),
            preserve_default=False,
        ),
    ]
