# Generated by Django 5.1.7 on 2025-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_meeting',
            field=models.DateField(verbose_name='Когда собираемся (дд.мм.гггг)'),
        ),
    ]
