# Generated by Django 5.1.7 on 2025-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_meeting',
            field=models.DateField(verbose_name='Когда собираемся'),
        ),
    ]
