# Generated by Django 5.1.7 on 2025-03-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_alter_meeting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.URLField(blank=True, default='Ссылки нет - чекаем газеты', verbose_name='Ссылка на место, мероприятие'),
        ),
    ]
