# Generated by Django 5.1.7 on 2025-03-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_alter_meeting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
